# -*- coding: utf-8 -*-
"""Number System Number Base.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LG-L887qGW_LPSq6pozpdtETQxIHaxAl
"""

dec = 110354120
print(dec,  "in Heximal: ", hex(dec) )

dec = 34
print(dec,  "in Binary: ", bin(dec) )

dec = 110354120
print(dec,  "in Octal: ", oct(dec) )

#Base 10 to Base 16

binary='2010511101001'
# print(binary, 'in Decimal: ', int(binary, 10))
print(binary, 'in Heximal: ', hex(int(binary, 10)))